#!/usr/bin/env bash

# bspwm config dir
BSPDIR="$HOME/.config/bspwm"

# forgot what this does
export PATH="${PATH}:$HOME/.config/bspwm/bin"

# fixes java based software
export _JAVA_AWT_WM_NONREPARENTING=1

# below is for pywal set to xresources colors, if you dont have pywal or a xresources file it wont work

# Set the border colors.

. "${HOME}/.cache/wal/colors.sh"

bspc config normal_border_color "$color1"
bspc config active_border_color "$color2"
bspc config focused_border_color "$color15"
# Use the line below if you are on bspwm >= 0.9.4
bspc config presel_feedback_color "$color1"
# Use the line below if you are on bspwm < 0.9.4
#bspc config presel_border_color "$color1"

CURRENT_BORDER='3'
CURRENT_GAP='17.5'
CURRENT_SRATIO='1.4'

xrandr --output HDMI-0 --mode 2560x1440 --rate 144 &
 
bspc monitor HDMI-0 -d '1' '2' '3' '4' '5'

bspc config border_width "$CURRENT_BORDER"
bspc config window_gap "$CURRENT_GAP"
bspc config split_ratio "$CURRENT_SRATIO"
bspc config focused_border_color "$BLUE" 
bspc config normal_border_color "$BACKGROUND"
bspc config active_border_color "$MAGENTA"
bspc config presel_feedback_color "$GREEN"
bspc config borderless_monocle true
bspc config gapless_monocle true
bspc config paddingless_monocle true
bspc config single_monocle false
bspc config focus_follows_pointer true

bspc wm --adopt-orphans

# remove all rules first
bspc rule -r *:*

declare -a floating=(alacritty-float Pcmanfm Thunar Onboard Yad 'Firefox:Places' \
Viewnior feh Nm-connection-editor)
for i in ${floating[@]}; do
   bspc rule -a $i state=floating follow=on focus=on; done

bspc rule -a Conky state=floating manage=off
bspc rule -a stalonetray state=floating manage=off

# kills shume shit
killall -9 xsettingsd sxhkd dunst ksuperkey ffplay polybar xsetroot picom easyeffects sh feh cava zscroll

# launches x settings config
xsettingsd --config /home/asakusa/.config/bspwm/xsettingsd &


# Lauch keybindings daemon
sxhkd -c .config/bspwm/sxhkdrc &

# fixes rofi so super is launcher
if pgrep -x rofi; then
    killall rofi
else
ksuperkey -e 'Super_L=Alt_L|F1' &
fi


# fixez cursor
xsetroot -cursor_name left_ptr &

# restore feh wallpaper


# polybar -c .config/bspwm/polybar/poly2/config.ini &
./.fehbg &
bspcomp &
bspbar &
bspdunst &
easyeffects --gapplication-service &
sleep 0.8
ffplay -nodisp -autoexit Downloads/sony_psp_boot_sound-640521.mp3 &
sleep 4
ffplay -nodisp -autoexit /home/asakusa/Downloads/sony_psp_umd_boot_sound-640520.mp3 &
dunstify -u low -h string: "Welcome back, asakusa"
;
; ██▓    ▄▄▄       ██▀███   ██▀███ ▓██   ██▓▓█████  ██▓  ▄████  ██░ ██ ▄▄▄█████▓▓██   ██▓
;▓██▒   ▒████▄    ▓██ ▒ ██▒▓██ ▒ ██▒▒██  ██▒▓█   ▀ ▓██▒ ██▒ ▀█▒▓██░ ██▒▓  ██▒ ▓▒ ▒██  ██▒
;▒██░   ▒██  ▀█▄  ▓██ ░▄█ ▒▓██ ░▄█ ▒ ▒██ ██░▒███   ▒██▒▒██░▄▄▄░▒██▀▀██░▒ ▓██░ ▒░  ▒██ ██░
;▒██░   ░██▄▄▄▄██ ▒██▀▀█▄  ▒██▀▀█▄   ░ ▐██▓░▒▓█  ▄ ░██░░▓█  ██▓░▓█ ░██ ░ ▓██▓ ░   ░ ▐██▓░
;░██████▒▓█   ▓██▒░██▓ ▒██▒░██▓ ▒██▒ ░ ██▒▓░░▒████▒░██░░▒▓███▀▒░▓█▒░██▓  ▒██▒ ░   ░ ██▒▓░
;░ ▒░▓  ░▒▒   ▓▒█░░ ▒▓ ░▒▓░░ ▒▓ ░▒▓░  ██▒▒▒ ░░ ▒░ ░░▓   ░▒   ▒  ▒ ░░▒░▒  ▒ ░░      ██▒▒▒ 
;░ ░ ▒  ░ ▒   ▒▒ ░  ░▒ ░ ▒░  ░▒ ░ ▒░▓██ ░▒░  ░ ░  ░ ▒ ░  ░   ░  ▒ ░▒░ ░    ░     ▓██ ░▒░ 
;  ░ ░    ░   ▒     ░░   ░   ░░   ░ ▒ ▒ ░░     ░    ▒ ░░ ░   ░  ░  ░░ ░  ░       ▒ ▒ ░░  
;    ░  ░     ░  ░   ░        ░     ░ ░        ░  ░ ░        ░  ░  ░  ░          ░ ░     
;                                   ░ ░                                          ░ ░     
;
